config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :root
  get 'tasks/new', to: 'tasks#new', as: :task_new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update', as: :task_update
  delete 'tasks/:id', to: 'tasks#destroy'

  # put 'tasks/:id', to: 'tasks#update', as: :task_update

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task_upd = Task.find(params[:id])
    @task_upd.update(task_params)
    redirect_to task_path(@task_upd)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end





  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Your task details to be edited</h1>
<%= form_for @task do |f| %>
  Title: <%= f.text_field :title %>
  Details : <%= f.text_field :details %>
  Status : <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<%@tasks.each do |task|%>
  <p>
  <%=link_to '🗑️', task_path(task), method: :delete %>
  <%=task.completed == true ? '✅' : '😅'%>
  <%=link_to(task.title, task_path(task.id))%>


  </p>
<%end%>

<br>
<%= link_to('New task', task_new_path) %>
<br>

app/views/tasks/new.html.erb
<h1>Your new task details</h1>
<%= form_for @task do |f| %>
  Title: <%= f.text_field :title %>
  Details : <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>My TO DO's details</h1>
</ol>
  <li>Title: <%= @task.title %></li>
  <li>Details: <%= @task.details %></li>
  <li>Status: <%= 'Done' if @task.completed == true %></li>
<ol>

<div>
<%= link_to('Update task', task_edit_path) %>
</div>
<br>
<div>
<%= link_to('Back to task overview', tasks_path) %>
</div>